export const emojis = {
  fruits: [
    {
      slug: "grapes",
      character: "🍇",
      unicodeName: "grapes",
      codePoint: "1F347",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "melon",
      character: "🍈",
      unicodeName: "melon",
      codePoint: "1F348",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "watermelon",
      character: "🍉",
      unicodeName: "watermelon",
      codePoint: "1F349",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "tangerine",
      character: "🍊",
      unicodeName: "tangerine",
      codePoint: "1F34A",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "lemon",
      character: "🍋",
      unicodeName: "lemon",
      codePoint: "1F34B",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "banana",
      character: "🍌",
      unicodeName: "banana",
      codePoint: "1F34C",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "pineapple",
      character: "🍍",
      unicodeName: "pineapple",
      codePoint: "1F34D",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "mango",
      character: "🥭",
      unicodeName: "mango",
      codePoint: "1F96D",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "red-apple",
      character: "🍎",
      unicodeName: "red apple",
      codePoint: "1F34E",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "green-apple",
      character: "🍏",
      unicodeName: "green apple",
      codePoint: "1F34F",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "pear",
      character: "🍐",
      unicodeName: "pear",
      codePoint: "1F350",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "peach",
      character: "🍑",
      unicodeName: "peach",
      codePoint: "1F351",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "cherries",
      character: "🍒",
      unicodeName: "cherries",
      codePoint: "1F352",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "strawberry",
      character: "🍓",
      unicodeName: "strawberry",
      codePoint: "1F353",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "blueberries",
      character: "🫐",
      unicodeName: "blueberries",
      codePoint: "1FAD0",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "kiwi-fruit",
      character: "🥝",
      unicodeName: "kiwi fruit",
      codePoint: "1F95D",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "olive",
      character: "🫒",
      unicodeName: "olive",
      codePoint: "1FAD2",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "coconut",
      character: "🥥",
      unicodeName: "coconut",
      codePoint: "1F965",
      group: "food-drink",
      subGroup: "food-fruit",
    },
  ],
  vegetables: [
    {
      slug: "avocado",
      character: "🥑",
      unicodeName: "avocado",
      codePoint: "1F951",
      group: "food-drink",
      subGroup: "food-vegetable",
    },
    {
      slug: "eggplant",
      character: "🍆",
      unicodeName: "eggplant",
      codePoint: "1F346",
      group: "food-drink",
      subGroup: "food-vegetable",
    },
    {
      slug: "tomato",
      character: "🍅",
      unicodeName: "tomato",
      codePoint: "1F345",
      group: "food-drink",
      subGroup: "food-fruit",
    },
    {
      slug: "potato",
      character: "🥔",
      unicodeName: "potato",
      codePoint: "1F954",
      group: "food-drink",
      subGroup: "food-vegetable",
    },
    {
      slug: "carrot",
      character: "🥕",
      unicodeName: "carrot",
      codePoint: "1F955",
      group: "food-drink",
      subGroup: "food-vegetable",
    },
    {
      slug: "ear-of-corn",
      character: "🌽",
      unicodeName: "ear of corn",
      codePoint: "1F33D",
      group: "food-drink",
      subGroup: "food-vegetable",
    },
    {
      slug: "hot-pepper",
      character: "🌶️",
      unicodeName: "hot pepper",
      codePoint: "1F336 FE0F",
      group: "food-drink",
      subGroup: "food-vegetable",
    },
    {
      slug: "bell-pepper",
      character: "🫑",
      unicodeName: "bell pepper",
      codePoint: "1FAD1",
      group: "food-drink",
      subGroup: "food-vegetable",
    },
    {
      slug: "cucumber",
      character: "🥒",
      unicodeName: "cucumber",
      codePoint: "1F952",
      group: "food-drink",
      subGroup: "food-vegetable",
    },
    {
      slug: "leafy-green",
      character: "🥬",
      unicodeName: "leafy green",
      codePoint: "1F96C",
      group: "food-drink",
      subGroup: "food-vegetable",
    },
    {
      slug: "broccoli",
      character: "🥦",
      unicodeName: "broccoli",
      codePoint: "1F966",
      group: "food-drink",
      subGroup: "food-vegetable",
    },
    {
      slug: "garlic",
      character: "🧄",
      unicodeName: "garlic",
      codePoint: "1F9C4",
      group: "food-drink",
      subGroup: "food-vegetable",
    },
    {
      slug: "onion",
      character: "🧅",
      unicodeName: "onion",
      codePoint: "1F9C5",
      group: "food-drink",
      subGroup: "food-vegetable",
    },
    {
      slug: "mushroom",
      character: "🍄",
      unicodeName: "mushroom",
      codePoint: "1F344",
      group: "food-drink",
      subGroup: "food-vegetable",
    },
    {
      slug: "peanuts",
      character: "🥜",
      unicodeName: "peanuts",
      codePoint: "1F95C",
      group: "food-drink",
      subGroup: "food-vegetable",
    },
    {
      slug: "chestnut",
      character: "🌰",
      unicodeName: "chestnut",
      codePoint: "1F330",
      group: "food-drink",
      subGroup: "food-vegetable",
    },
  ],

  meat: [
    {
      slug: "meat-on-bone",
      character: "🍖",
      unicodeName: "meat on bone",
      codePoint: "1F356",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "poultry-leg",
      character: "🍗",
      unicodeName: "poultry leg",
      codePoint: "1F357",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "cut-of-meat",
      character: "🥩",
      unicodeName: "cut of meat",
      codePoint: "1F969",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "bacon",
      character: "🥓",
      unicodeName: "bacon",
      codePoint: "1F953",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "hamburger",
      character: "🍔",
      unicodeName: "hamburger",
      codePoint: "1F354",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "hot-dog",
      character: "🌭",
      unicodeName: "hot dog",
      codePoint: "1F32D",
      group: "food-drink",
      subGroup: "food-prepared",
    },
  ],
  dairy: [
    {
      slug: "cheese-wedge",
      character: "🧀",
      unicodeName: "cheese wedge",
      codePoint: "1F9C0",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "butter",
      character: "🧈",
      unicodeName: "butter",
      codePoint: "1F9C8",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "baby-bottle",
      character: "🍼",
      unicodeName: "baby bottle",
      codePoint: "1F37C",
      group: "food-drink",
      subGroup: "drink",
    },
    {
      slug: "glass-of-milk",
      character: "🥛",
      unicodeName: "glass of milk",
      codePoint: "1F95B",
      group: "food-drink",
      subGroup: "drink",
    },
  ],
  pantry: [
    {
      slug: "bread",
      character: "🍞",
      unicodeName: "bread",
      codePoint: "1F35E",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "croissant",
      character: "🥐",
      unicodeName: "croissant",
      codePoint: "1F950",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "baguette-bread",
      character: "🥖",
      unicodeName: "baguette bread",
      codePoint: "1F956",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "flatbread",
      character: "🫓",
      unicodeName: "flatbread",
      codePoint: "1FAD3",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "pretzel",
      character: "🥨",
      unicodeName: "pretzel",
      codePoint: "1F968",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "bagel",
      character: "🥯",
      unicodeName: "bagel",
      codePoint: "1F96F",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "pancakes",
      character: "🥞",
      unicodeName: "pancakes",
      codePoint: "1F95E",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "waffle",
      character: "🧇",
      unicodeName: "waffle",
      codePoint: "1F9C7",
      group: "food-drink",
      subGroup: "food-prepared",
    },

    {
      slug: "french-fries",
      character: "🍟",
      unicodeName: "french fries",
      codePoint: "1F35F",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "pizza",
      character: "🍕",
      unicodeName: "pizza",
      codePoint: "1F355",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "sandwich",
      character: "🥪",
      unicodeName: "sandwich",
      codePoint: "1F96A",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "taco",
      character: "🌮",
      unicodeName: "taco",
      codePoint: "1F32E",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "burrito",
      character: "🌯",
      unicodeName: "burrito",
      codePoint: "1F32F",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "tamale",
      character: "🫔",
      unicodeName: "tamale",
      codePoint: "1FAD4",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "stuffed-flatbread",
      character: "🥙",
      unicodeName: "stuffed flatbread",
      codePoint: "1F959",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "falafel",
      character: "🧆",
      unicodeName: "falafel",
      codePoint: "1F9C6",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "egg",
      character: "🥚",
      unicodeName: "egg",
      codePoint: "1F95A",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "cooking",
      character: "🍳",
      unicodeName: "cooking",
      codePoint: "1F373",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "shallow-pan-of-food",
      character: "🥘",
      unicodeName: "shallow pan of food",
      codePoint: "1F958",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "pot-of-food",
      character: "🍲",
      unicodeName: "pot of food",
      codePoint: "1F372",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "fondue",
      character: "🫕",
      unicodeName: "fondue",
      codePoint: "1FAD5",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "bowl-with-spoon",
      character: "🥣",
      unicodeName: "bowl with spoon",
      codePoint: "1F963",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "green-salad",
      character: "🥗",
      unicodeName: "green salad",
      codePoint: "1F957",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "popcorn",
      character: "🍿",
      unicodeName: "popcorn",
      codePoint: "1F37F",
      group: "food-drink",
      subGroup: "food-prepared",
    },

    {
      slug: "salt",
      character: "🧂",
      unicodeName: "salt",
      codePoint: "1F9C2",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "canned-food",
      character: "🥫",
      unicodeName: "canned food",
      codePoint: "1F96B",
      group: "food-drink",
      subGroup: "food-prepared",
    },
    {
      slug: "bento-box",
      character: "🍱",
      unicodeName: "bento box",
      codePoint: "1F371",
      group: "food-drink",
      subGroup: "food-asian",
    },
    {
      slug: "rice-cracker",
      character: "🍘",
      unicodeName: "rice cracker",
      codePoint: "1F358",
      group: "food-drink",
      subGroup: "food-asian",
    },
    {
      slug: "rice-ball",
      character: "🍙",
      unicodeName: "rice ball",
      codePoint: "1F359",
      group: "food-drink",
      subGroup: "food-asian",
    },
    {
      slug: "cooked-rice",
      character: "🍚",
      unicodeName: "cooked rice",
      codePoint: "1F35A",
      group: "food-drink",
      subGroup: "food-asian",
    },
    {
      slug: "curry-rice",
      character: "🍛",
      unicodeName: "curry rice",
      codePoint: "1F35B",
      group: "food-drink",
      subGroup: "food-asian",
    },
    {
      slug: "steaming-bowl",
      character: "🍜",
      unicodeName: "steaming bowl",
      codePoint: "1F35C",
      group: "food-drink",
      subGroup: "food-asian",
    },
    {
      slug: "spaghetti",
      character: "🍝",
      unicodeName: "spaghetti",
      codePoint: "1F35D",
      group: "food-drink",
      subGroup: "food-asian",
    },
    {
      slug: "roasted-sweet-potato",
      character: "🍠",
      unicodeName: "roasted sweet potato",
      codePoint: "1F360",
      group: "food-drink",
      subGroup: "food-asian",
    },
    {
      slug: "oden",
      character: "🍢",
      unicodeName: "oden",
      codePoint: "1F362",
      group: "food-drink",
      subGroup: "food-asian",
    },
    {
      slug: "sushi",
      character: "🍣",
      unicodeName: "sushi",
      codePoint: "1F363",
      group: "food-drink",
      subGroup: "food-asian",
    },
    {
      slug: "fried-shrimp",
      character: "🍤",
      unicodeName: "fried shrimp",
      codePoint: "1F364",
      group: "food-drink",
      subGroup: "food-asian",
    },
    {
      slug: "fish-cake-with-swirl",
      character: "🍥",
      unicodeName: "fish cake with swirl",
      codePoint: "1F365",
      group: "food-drink",
      subGroup: "food-asian",
    },
    {
      slug: "moon-cake",
      character: "🥮",
      unicodeName: "moon cake",
      codePoint: "1F96E",
      group: "food-drink",
      subGroup: "food-asian",
    },
    {
      slug: "dango",
      character: "🍡",
      unicodeName: "dango",
      codePoint: "1F361",
      group: "food-drink",
      subGroup: "food-asian",
    },
    {
      slug: "dumpling",
      character: "🥟",
      unicodeName: "dumpling",
      codePoint: "1F95F",
      group: "food-drink",
      subGroup: "food-asian",
    },
    {
      slug: "fortune-cookie",
      character: "🥠",
      unicodeName: "fortune cookie",
      codePoint: "1F960",
      group: "food-drink",
      subGroup: "food-asian",
    },
    {
      slug: "takeout-box",
      character: "🥡",
      unicodeName: "takeout box",
      codePoint: "1F961",
      group: "food-drink",
      subGroup: "food-asian",
    },
    {
      slug: "crab",
      character: "🦀",
      unicodeName: "crab",
      codePoint: "1F980",
      group: "food-drink",
      subGroup: "food-marine",
    },
    {
      slug: "lobster",
      character: "🦞",
      unicodeName: "lobster",
      codePoint: "1F99E",
      group: "food-drink",
      subGroup: "food-marine",
    },
    {
      slug: "shrimp",
      character: "🦐",
      unicodeName: "shrimp",
      codePoint: "1F990",
      group: "food-drink",
      subGroup: "food-marine",
    },
    {
      slug: "squid",
      character: "🦑",
      unicodeName: "squid",
      codePoint: "1F991",
      group: "food-drink",
      subGroup: "food-marine",
    },
    {
      slug: "oyster",
      character: "🦪",
      unicodeName: "oyster",
      codePoint: "1F9AA",
      group: "food-drink",
      subGroup: "food-marine",
    },
    {
      slug: "soft-ice-cream",
      character: "🍦",
      unicodeName: "soft ice cream",
      codePoint: "1F366",
      group: "food-drink",
      subGroup: "food-sweet",
    },
    {
      slug: "shaved-ice",
      character: "🍧",
      unicodeName: "shaved ice",
      codePoint: "1F367",
      group: "food-drink",
      subGroup: "food-sweet",
    },
    {
      slug: "ice-cream",
      character: "🍨",
      unicodeName: "ice cream",
      codePoint: "1F368",
      group: "food-drink",
      subGroup: "food-sweet",
    },
    {
      slug: "doughnut",
      character: "🍩",
      unicodeName: "doughnut",
      codePoint: "1F369",
      group: "food-drink",
      subGroup: "food-sweet",
    },
    {
      slug: "cookie",
      character: "🍪",
      unicodeName: "cookie",
      codePoint: "1F36A",
      group: "food-drink",
      subGroup: "food-sweet",
    },
    {
      slug: "birthday-cake",
      character: "🎂",
      unicodeName: "birthday cake",
      codePoint: "1F382",
      group: "food-drink",
      subGroup: "food-sweet",
    },
    {
      slug: "shortcake",
      character: "🍰",
      unicodeName: "shortcake",
      codePoint: "1F370",
      group: "food-drink",
      subGroup: "food-sweet",
    },
    {
      slug: "cupcake",
      character: "🧁",
      unicodeName: "cupcake",
      codePoint: "1F9C1",
      group: "food-drink",
      subGroup: "food-sweet",
    },
    {
      slug: "pie",
      character: "🥧",
      unicodeName: "pie",
      codePoint: "1F967",
      group: "food-drink",
      subGroup: "food-sweet",
    },
    {
      slug: "chocolate-bar",
      character: "🍫",
      unicodeName: "chocolate bar",
      codePoint: "1F36B",
      group: "food-drink",
      subGroup: "food-sweet",
    },
    {
      slug: "candy",
      character: "🍬",
      unicodeName: "candy",
      codePoint: "1F36C",
      group: "food-drink",
      subGroup: "food-sweet",
    },
    {
      slug: "lollipop",
      character: "🍭",
      unicodeName: "lollipop",
      codePoint: "1F36D",
      group: "food-drink",
      subGroup: "food-sweet",
    },
    {
      slug: "custard",
      character: "🍮",
      unicodeName: "custard",
      codePoint: "1F36E",
      group: "food-drink",
      subGroup: "food-sweet",
    },
    {
      slug: "honey-pot",
      character: "🍯",
      unicodeName: "honey pot",
      codePoint: "1F36F",
      group: "food-drink",
      subGroup: "food-sweet",
    },
  ],
  drink: [

    {
      slug: "hot-beverage",
      character: "☕",
      unicodeName: "hot beverage",
      codePoint: "2615",
      group: "food-drink",
      subGroup: "drink",
    },
    {
      slug: "teapot",
      character: "🫖",
      unicodeName: "teapot",
      codePoint: "1FAD6",
      group: "food-drink",
      subGroup: "drink",
    },
    {
      slug: "teacup-without-handle",
      character: "🍵",
      unicodeName: "teacup without handle",
      codePoint: "1F375",
      group: "food-drink",
      subGroup: "drink",
    },
    {
      slug: "sake",
      character: "🍶",
      unicodeName: "sake",
      codePoint: "1F376",
      group: "food-drink",
      subGroup: "drink",
    },
    {
      slug: "bottle-with-popping-cork",
      character: "🍾",
      unicodeName: "bottle with popping cork",
      codePoint: "1F37E",
      group: "food-drink",
      subGroup: "drink",
    },
    {
      slug: "wine-glass",
      character: "🍷",
      unicodeName: "wine glass",
      codePoint: "1F377",
      group: "food-drink",
      subGroup: "drink",
    },
    {
      slug: "cocktail-glass",
      character: "🍸",
      unicodeName: "cocktail glass",
      codePoint: "1F378",
      group: "food-drink",
      subGroup: "drink",
    },
    {
      slug: "tropical-drink",
      character: "🍹",
      unicodeName: "tropical drink",
      codePoint: "1F379",
      group: "food-drink",
      subGroup: "drink",
    },
    {
      slug: "beer-mug",
      character: "🍺",
      unicodeName: "beer mug",
      codePoint: "1F37A",
      group: "food-drink",
      subGroup: "drink",
    },
    {
      slug: "clinking-beer-mugs",
      character: "🍻",
      unicodeName: "clinking beer mugs",
      codePoint: "1F37B",
      group: "food-drink",
      subGroup: "drink",
    },
    {
      slug: "clinking-glasses",
      character: "🥂",
      unicodeName: "clinking glasses",
      codePoint: "1F942",
      group: "food-drink",
      subGroup: "drink",
    },
    {
      slug: "tumbler-glass",
      character: "🥃",
      unicodeName: "tumbler glass",
      codePoint: "1F943",
      group: "food-drink",
      subGroup: "drink",
    },
    {
      slug: "cup-with-straw",
      character: "🥤",
      unicodeName: "cup with straw",
      codePoint: "1F964",
      group: "food-drink",
      subGroup: "drink",
    },
    {
      slug: "bubble-tea",
      character: "🧋",
      unicodeName: "bubble tea",
      codePoint: "1F9CB",
      group: "food-drink",
      subGroup: "drink",
    },
    {
      slug: "beverage-box",
      character: "🧃",
      unicodeName: "beverage box",
      codePoint: "1F9C3",
      group: "food-drink",
      subGroup: "drink",
    },
    {
      slug: "mate",
      character: "🧉",
      unicodeName: "mate",
      codePoint: "1F9C9",
      group: "food-drink",
      subGroup: "drink",
    },
    {
      slug: "ice",
      character: "🧊",
      unicodeName: "ice",
      codePoint: "1F9CA",
      group: "food-drink",
      subGroup: "drink",
    },
  ],
  dishware: [
    {
      slug: "chopsticks",
      character: "🥢",
      unicodeName: "chopsticks",
      codePoint: "1F962",
      group: "food-drink",
      subGroup: "dishware",
    },
    {
      slug: "fork-and-knife-with-plate",
      character: "🍽️",
      unicodeName: "fork and knife with plate",
      codePoint: "1F37D FE0F",
      group: "food-drink",
      subGroup: "dishware",
    },
    {
      slug: "fork-and-knife",
      character: "🍴",
      unicodeName: "fork and knife",
      codePoint: "1F374",
      group: "food-drink",
      subGroup: "dishware",
    },
    {
      slug: "spoon",
      character: "🥄",
      unicodeName: "spoon",
      codePoint: "1F944",
      group: "food-drink",
      subGroup: "dishware",
    },
    {
      slug: "kitchen-knife",
      character: "🔪",
      unicodeName: "kitchen knife",
      codePoint: "1F52A",
      group: "food-drink",
      subGroup: "dishware",
    },
    {
      slug: "amphora",
      character: "🏺",
      unicodeName: "amphora",
      codePoint: "1F3FA",
      group: "food-drink",
      subGroup: "dishware",
    },
  ],
};
